"""MC-02 operational rule aliases.

This file exposes the configuration values used by processors and validators:
birth cohort month ``Mes_Nac``, province ``provincia``, insurance ``Obs_Niño``,
denominator ``Registros``, active component flags and current local omissions
for CRED and DNI within 30 days.
"""

from .config import CODIGOS_ESTANDAR, REGLAS_NEGOCIO


DENOMINATOR_COLUMN = REGLAS_NEGOCIO["COLUMNA_DENOMINADOR"]
NUMERATOR_COLUMN = REGLAS_NEGOCIO["COLUMNA_NUMERADOR_OPERATIVO"]
MONTH_COLUMN = REGLAS_NEGOCIO["COLUMNA_MES_EVALUACION"]
PROVINCE_COLUMN = REGLAS_NEGOCIO["COLUMNA_PROVINCIA"]
INSURANCE_COLUMN = REGLAS_NEGOCIO["COLUMNA_TIPO_SEGURO"]

INCLUDED_DENOMINATOR_VALUE = REGLAS_NEGOCIO["VALOR_DENOMINADOR"]
INCLUDED_PROVINCE_DEFAULT = REGLAS_NEGOCIO["PROVINCIA_DEFECTO"]
INCLUDED_INSURANCE_TYPES = REGLAS_NEGOCIO["SEGUROS_INCLUIDOS"]
EXCLUSION_CRITERIA = REGLAS_NEGOCIO["CRITERIOS_EXCLUSION"]
OMITTED_CURRENT_CRITERIA = REGLAS_NEGOCIO["CRITERIOS_OMITIDOS_ACTUALMENTE"]
ACTIVE_COMPONENT_FLAGS = REGLAS_NEGOCIO["COMPONENTES_ACTIVOS"]
