"""MC-02 operational rules based on the processed Excel."""

from .config import CODIGOS_ESTANDAR, REGLAS_NEGOCIO


DENOMINATOR_COLUMN = REGLAS_NEGOCIO["COLUMNA_DENOMINADOR"]
NUMERATOR_COLUMN = REGLAS_NEGOCIO["COLUMNA_NUMERADOR_OPERATIVO"]
MONTH_COLUMN = REGLAS_NEGOCIO["COLUMNA_MES_EVALUACION"]
PROVINCE_COLUMN = REGLAS_NEGOCIO["COLUMNA_PROVINCIA"]
INSURANCE_COLUMN = REGLAS_NEGOCIO["COLUMNA_TIPO_SEGURO"]

INCLUDED_DENOMINATOR_VALUE = REGLAS_NEGOCIO["VALOR_DENOMINADOR"]
INCLUDED_PROVINCE_DEFAULT = REGLAS_NEGOCIO["PROVINCIA_DEFECTO"]
INCLUDED_INSURANCE_TYPES = REGLAS_NEGOCIO["SEGUROS_INCLUIDOS"]
EXCLUSION_CRITERIA = REGLAS_NEGOCIO["CRITERIOS_EXCLUSION"]
OMITTED_CURRENT_CRITERIA = REGLAS_NEGOCIO["CRITERIOS_OMITIDOS_ACTUALMENTE"]
ACTIVE_COMPONENT_FLAGS = REGLAS_NEGOCIO["COMPONENTES_ACTIVOS"]
