"""Active MC-02 component catalog."""

from .hemoglobin import HEMOGLOBIN_COMPONENTS, HEMOGLOBIN_WINDOWS
from .iron import IRON_COMPONENTS, IRON_WINDOWS
from .vaccines import VACCINE_COMPONENTS, VACCINE_WINDOWS


COMPONENTS = [
    *VACCINE_COMPONENTS,
    *IRON_COMPONENTS,
    *HEMOGLOBIN_COMPONENTS,
]

COMPONENT_WINDOWS = {
    **VACCINE_WINDOWS,
    **IRON_WINDOWS,
    **HEMOGLOBIN_WINDOWS,
}

__all__ = [
    "COMPONENTS",
    "COMPONENT_WINDOWS",
    "HEMOGLOBIN_COMPONENTS",
    "HEMOGLOBIN_WINDOWS",
    "IRON_COMPONENTS",
    "IRON_WINDOWS",
    "VACCINE_COMPONENTS",
    "VACCINE_WINDOWS",
]
