"""SI-02 indicator configuration and Excel contract."""

from __future__ import annotations

from dataclasses import dataclass


CODE = "si02"
NAME = "Suplementacion con hierro y dosajes de hemoglobina"
DEFAULT_PROVINCE = "ABANCAY"
DEFAULT_TARGET_COVERAGE = 65.0
ALL_PROVINCES_TOKEN = "__ALL__"

DETAIL_SHEET = "Detalle_Ate"
SUMMARY_RED_SHEET = "Resumen_Red"
SUMMARY_UBIGEO_SHEET = "Resumen_Ubigeo"

DOSAGE_CODES = {"85018", "85018.01", "85031"}
ANEMIA_CODES = {"D509", "D649"}
IRON_CODES = {"99199.17", "99199.19"}
TELEMEDICINE_CODE = "99499"


@dataclass(frozen=True)
class SubindicatorSpec:
    code: str
    official_code: str
    title: str
    header_row: int
    cutoff_cell: str
    province_column: str
    month_column: str
    status_column: str
    status_flag_column: str
    target_coverage: float
    required_columns: tuple[str, ...]
    optional_columns: tuple[str, ...] = ()
    identifier_tokens: tuple[str, ...] = ()


COMMON_COLUMNS = (
    "UBIGEO",
    "distrito",
    "des_red",
    "des_micro",
    "Renaes_ate",
    "EESS",
    "afi_dni",
    "NUMCNV",
    "NOMBRE",
    "APELLPAT",
    "APEMAT",
    "FEC_NAC",
    "EESS_NAC",
    "APELLNOM_MADRE",
    "DNI_MADRE",
    "CELULAR",
    "TIPO_SEGURO",
    "Peso",
    "SEMANAGESTACION",
    "EdadDias",
    "mes_eva",
    "registros",
    "ano",
)


SI0201_COLUMNS = COMMON_COLUMNS + (
    "PROVINCIA",
    "fec_Anemia",
    "Codigo_Item",
    "Valor_Lab",
    "Obser_Anemia",
    "Ate_HIS",
    "obs_Cnv",
    "Obs_Ind",
    "Cumple_4Mes",
    "mes_Nac",
    "Fec_H2",
    "Cie_H2",
    "Lab_H2",
    "Reg_H2",
    "EESS_H2",
    "Prof_H2",
    "Intervalo3",
    "Obs_hierro",
    "Fec_Dh3",
    "Cie_Dh3",
    "Lab_Dh3",
    "Reg_Dh3",
    "EESS_Dh3",
    "Prof_Dh3",
    "Intervalo5",
    "Obs_DH",
    "Fec_TA3",
    "Cie_TA3",
    "Lab_TA3",
    "Reg_TA3",
    "EESS_TA3",
    "Prof_TA3",
    "Intervalo6",
    "Obs_TA",
    "Obs_General",
    "Obs_General1",
    "Obs_hierro1",
    "Obs_DH1",
    "Obs_TA1",
)

SI0202_COLUMNS = COMMON_COLUMNS + (
    "provincia",
    "fec_Anemia",
    "Codigo_Item",
    "Valor_Lab",
    "Obs_Anemia",
    "Ate_HIS",
    "fec_premat",
    "EESS_Premat",
    "Reg_Premat",
    "obs_Cnv",
    "Obs_Ind",
    "Cumple_4Mes",
    "Mes_Nac",
    "Fec_Dh1",
    "Cie_Dh1",
    "lab_Dh1",
    "Reg_Dh1",
    "EESS_Dh1",
    "Prof_Dh1",
    "Intervalo1",
    "Fec_H1",
    "Cie_H1",
    "Lab_H1",
    "Reg_H1",
    "EESS_H1",
    "Prof_H1",
    "Intervalo2",
    "Fec_H2",
    "Cie_H2",
    "Lab_H2",
    "Reg_H2",
    "EESS_H2",
    "Prof_H2",
    "Intervalo3",
    "Fec_Dh2",
    "Cie_Dh2",
    "Lab_Dh2",
    "Reg_Dh2",
    "EESS_DH2",
    "Prof_Dh2",
    "Intervalo4",
    "Fec_Dh3",
    "Cie_Dh3",
    "Lab_Dh3",
    "Reg_Dh3",
    "EESS_Dh3",
    "Prof_Dh3",
    "Intervalo5",
    "Fec_TA3",
    "Cie_TA3",
    "Lab_TA3",
    "Reg_TA3",
    "EESS_TA3",
    "Prof_TA3",
    "Intervalo6",
    "obser_Cumple",
    "estado",
    "DH_1Mes",
    "H1_1Mes",
    "H2_4Mes",
    "DH2_3Mes",
    "DH3_6Mes",
)

SI0203_COLUMNS = COMMON_COLUMNS + (
    "provincia",
    "obs_Cnv",
    "fec_Anemia",
    "Ci10_Anemia",
    "Lab_Anemia",
    "reg_Anemia",
    "Prof_Anemia",
    "EESS_Anemia",
    "Obser_Anemia",
    "fec_DH",
    "Ci10_Dh",
    "lab_Dh",
    "reg_dh",
    "Cumple_6Meses",
    "Fec_hierro1",
    "Cie10_Anemia1",
    "Cie10_Hierro1",
    "lab_hierro1",
    "Reg_Hierro1",
    "EESS_AteHierro1",
    "Prof_AteHierro1",
    "Intervalo1",
    "Fec_DH1",
    "Cie_Dh1",
    "Lab_Dh1",
    "Reg_Dh1",
    "EESS_AteDH",
    "Prof_AteDH1",
    "intervaloDh1",
    "Obse_Dh1m",
    "Fec_hierro2",
    "Cie10_Anemia2",
    "Cie10_Hierro2",
    "lab_hierro2",
    "Reg_Hierro2",
    "EESS_AteHierro2",
    "Prof_AteHierro2",
    "Intervalo2",
    "Fec_DH2",
    "Cie_Dh2",
    "Lab_Dh2",
    "Reg_Dh2",
    "EESS_AteDH2",
    "Prof_AteDH2",
    "intervaloDh2",
    "Obse_Dh2m",
    "Fec_hierro3",
    "Cie10_Anemia3",
    "Cie10_Hierro3",
    "lab_hierro3",
    "Reg_Hierro3",
    "EESS_AteHierro3",
    "Prof_AteHierro3",
    "Intervalo3",
    "Fec_DH3",
    "Cie_Dh3",
    "Lab_Dh3",
    "Reg_Dh3",
    "EESS_AteDH3",
    "Prof_AteDH3",
    "intervaloDh3",
    "Obse_Dh3m",
    "Fec_hierro4",
    "Cie10_Anemia4",
    "Cie10_Hierro4",
    "lab_hierro4",
    "Reg_Hierro4",
    "EESS_AteHierro4",
    "Prof_AteHierro4",
    "Intervalo4",
    "Fec_hierro5",
    "Cie10_Anemia5",
    "Cie10_Hierro5",
    "lab_hierro5",
    "Reg_Hierro5",
    "EESS_AteHierro5",
    "Prof_AteHierro5",
    "Intervalo5",
    "Fec_hierro6",
    "Cie10_Anemia6",
    "Cie10_Hierro6",
    "lab_hierro6",
    "Reg_Hierro6",
    "EESS_AteHierro6",
    "Prof_AteHierro6",
    "Intervalo6",
    "Obs_Hierro",
    "Fec_TA1",
    "Cie10_Anemia7",
    "Cie10_TA1",
    "lab_TA1",
    "Reg_TA1",
    "EESS_TA1",
    "Prof_TA1",
    "intervaloTA",
    "Obse_TA",
    "Fec_DH12m",
    "Cie_Dh12m",
    "Lab_Dh12m",
    "Reg_Dh12m",
    "EESS_AteDH12m",
    "Prof_AteDh12m",
    "intervaloDh12m",
    "Obse_Dh12m",
    "Cumple_General",
    "estado",
    "Esta_Hierro",
    "Esta_TA",
    "Esta_DH1",
    "Esta_Dh2",
    "Esta_DH3",
    "Esta_Dh12m",
)

SI0204_COLUMNS = COMMON_COLUMNS + (
    "provincia",
    "obs_Cnv",
    "fec_Anemia",
    "Ci10_Anemia",
    "Lab_Anemia",
    "reg_Anemia",
    "Obser_Anemia",
    "fec_DH",
    "Ci10_Dh",
    "lab_Dh",
    "reg_dh",
    "Obs_Ind",
    "Cumple_6Meses",
    "Fec_hierro1",
    "Cie10_Hierro1",
    "lab_hierro1",
    "Reg_Hierro1",
    "EESS_AteHierro1",
    "Prof_AteHierro1",
    "Intervalo1",
    "Fec_hierro2",
    "Cie10_Hierro2",
    "lab_hierro2",
    "Reg_Hierro2",
    "EESS_AteHierro2",
    "Prof_AteHierro2",
    "Intervalo2",
    "Fec_hierro3",
    "Cie10_Hierro3",
    "lab_hierro3",
    "Reg_Hierro3",
    "EESS_AteHierro3",
    "Prof_AteHierro3",
    "Intervalo3",
    "Fec_hierro4",
    "Cie10_Hierro4",
    "lab_hierro4",
    "Reg_Hierro4",
    "EESS_AteHierro4",
    "Prof_AteHierro4",
    "Intervalo4",
    "Fec_DH1",
    "Cie_Dh1",
    "Lab_Dh1",
    "Reg_Dh1",
    "EESS_AteDH",
    "Prof_AteDH1",
    "intervaloDh1",
    "Obse_Dh1m",
    "Fec_hierro5",
    "Cie10_Hierro5",
    "lab_hierro5",
    "Reg_Hierro5",
    "EESS_AteHierro5",
    "Prof_AteHierro5",
    "Intervalo5",
    "Fec_hierro6",
    "Cie10_Hierro6",
    "lab_hierro6",
    "Reg_Hierro6",
    "EESS_AteHierro6",
    "Prof_AteHierro6",
    "Intervalo6",
    "Obs_Hierro",
    "Fec_TA1",
    "Cie10_TA1",
    "lab_TA1",
    "Reg_TA1",
    "EESS_TA1",
    "Prof_TA1",
    "intervaloTA",
    "Obse_TA",
    "Fec_DH12m",
    "Cie_Dh12m",
    "Lab_Dh12m",
    "Reg_Dh12m",
    "EESS_AteDH12m",
    "Prof_AteDh12m",
    "intervaloDh12m",
    "Obse_Dh12m",
    "Cumple_General",
    "estado",
    "Esta_Hierro",
    "Esta_TA",
    "Esta_DH1",
    "Esta_Dh12m",
)


SUBINDICATORS: dict[str, SubindicatorSpec] = {
    "si02_01": SubindicatorSpec(
        code="si02_01",
        official_code="SI-02.01",
        title="Condicion previa: hierro 4 meses y dosaje 6 meses",
        header_row=11,
        cutoff_cell="B9",
        province_column="PROVINCIA",
        month_column="mes_eva",
        status_column="Obs_General",
        status_flag_column="Obs_General1",
        target_coverage=92.0,
        required_columns=SI0201_COLUMNS,
        identifier_tokens=("Obs_General1", "Obs_hierro1", "Obs_DH1", "Obs_TA1"),
    ),
    "si02_02": SubindicatorSpec(
        code="si02_02",
        official_code="SI-02.02",
        title="Prematuros y/o bajo peso al nacer",
        header_row=10,
        cutoff_cell="B8",
        province_column="provincia",
        month_column="mes_eva",
        status_column="obser_Cumple",
        status_flag_column="estado",
        target_coverage=60.3,
        required_columns=SI0202_COLUMNS,
        identifier_tokens=("fec_premat", "DH_1Mes", "H1_1Mes", "H2_4Mes", "DH2_3Mes", "DH3_6Mes"),
    ),
    "si02_03": SubindicatorSpec(
        code="si02_03",
        official_code="SI-02.03",
        title="Doce meses con anemia",
        header_row=9,
        cutoff_cell="B8",
        province_column="provincia",
        month_column="mes_eva",
        status_column="Cumple_General",
        status_flag_column="estado",
        target_coverage=55.0,
        required_columns=SI0203_COLUMNS,
        identifier_tokens=("Prof_Anemia", "EESS_Anemia", "Obse_Dh2m", "Obse_Dh3m", "Esta_Dh2", "Esta_DH3"),
    ),
    "si02_04": SubindicatorSpec(
        code="si02_04",
        official_code="SI-02.04",
        title="Doce meses sin anemia",
        header_row=9,
        cutoff_cell="B8",
        province_column="provincia",
        month_column="mes_eva",
        status_column="Cumple_General",
        status_flag_column="estado",
        target_coverage=65.0,
        required_columns=SI0204_COLUMNS,
        identifier_tokens=("Obs_Ind", "Obse_Dh1m", "Obse_Dh12m", "Esta_Dh12m"),
    ),
}

EXPECTED_PACKAGE_CODES = tuple(SUBINDICATORS.keys())
